version: "3.3"
services:
  apcupsd_exporter:
    container_name: apcupsd_exporter
    stdin_open: true
    tty: true
    networks:
      - apcupsd
#    ports:
#      - 9162:9162
    image: apcupsd-exporter
    command: -apcupsd.addr apcupsd:3551;
networks:
  apcupsd:
    external: true

